### ISSUE TITLE
Difficult to navigate issues.

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-local_qtracker#16]
Entering an issue to respond or close, there is no easy way to return to the list of issues. Either going back or using the bread crumbs, one return to list of questions, and the issue list for the question has to be reopened manually.  Using the back button, the page is not updated, and using the breadcrumbs, the sort order is lost.

There is a need for a quick way to process many issues on the same question quickly.  They are often duplicates, and often related.  Showing the list for the question (from the list view) also in the single-issue view is a possible approach.

**Comment by andstor** [comment]
Release #32 introduces a way to navigate back to the list of issues with the help of breadcrumbs 🍞 Also, the newly added sidebar provides a quick way to process issues related to the same question.
