### ISSUE TITLE
View issues

### ISSUE THREAD

**Issue by andstor** [KQMATH/moodle-local_qtracker#2]
As a teacher, I want to be able to view the registered issues in a simple and organized table. This way, I am able to quickly resolve issues.

**Comment by andstor** [comment]
### Mockup of the issue view.

#### Table Options (Filtering )
> All options should be remembered by using the [Moodle Preference API](https://docs.moodle.org/dev/Preference_API)

- Filtering the issues by **State** and **Label** can be done with select inputs.
- The **Context** selection input should be present on all sites but activity modules. This makes it possible to filter issues by activity. 
- By toggling the "**Group by questions**", one should be able to aggregate questions with issues together.

<img src="https://user-images.githubusercontent.com/21249611/88062737-82854c80-cb69-11ea-9462-8c871bd3a8bb.png" width="500" />

**Comment by hgeorgsch** [comment]
Elaborated in #4 and #5 as two views.

**Comment by hgeorgsch** [comment]
The Mockup is good, but 
1. The context selector is superfluous, I think.   It is ok if it can be made more compact and can be made workable.
2.  All states (new, open, closed) should be listed in the same view.  Filtering is better done with check boxes. Sorting on the number of new/open questions is important.
3.  I am not sure about the meaning of «group by question».  What would we see if we uncheck?  Each issue on a separate row?  That could be useful, but they should still be grouped by question (suppressing closed issues), and the checkbox should then be called «aggregate each question».

**Comment by hgeorgsch** [comment]
This looks good.  Can it be closed, @andstor ?
