### ISSUE TITLE
View issue v2

### ISSUE THREAD

**Issue by andstor** [KQMATH/moodle-local_qtracker#26]
Following is a new mockup of the issue view, building upon #9. This new design should capture most of the functionality expressed in a number of issues. Primarily, this covers parts of issue #16 and #5, by adding a new side panel. Also, issue #13,  #7, #24 and #25 are related.

**Comment by andstor** [comment]
### Mockup of the improved issue view
#### Side panel - question issues
The new side panel to the left includes a list of all the issues for the question for the current viewed issue. Primarily, this list only includes `Open` and `New` issues. For easy navigation, it should be possible to toggle showing `Closed` issues as well. By clicking the  `Issue title`, one can navigate to the issue.

##### Dropdown menu
Each issue is presented with a small menu, indicated by three dots. This menu includes the options to `Close`/`Open` the issue. It also includes a option to `Subsume` the issue.

#### New buttons in top right corner
Two new buttons in the top right corner has been added. This includes a `New issue` button. This is a redirect to the page for creating a new manual issue. See #24. This button should also be added to the *Issues view page*. The other button enables the user to rename the issue title. By clicking the button, the Issue title should be converted to an input field, along with presenting a `Save` and `Cancel` button and 

#### Advanced dropdown menus
Ion order to manage (add, remove, etc.) tags and linked issues, an advanced dropdown menu should be presented when clicking the gear icons under the *Tag s* and *Linked issues* sections. This menu should include a search field, to be able to search for issues or tags.

#### Subsuming issues
By subsuming an issue, the selected issue in the side panel will be closed and listed under `Linked issues` in the section to the right. When viewing a linked issue, a banner at the top will state that this issue is referenced, together with a link to the referencing issues. See second mockup.

<img src="https://user-images.githubusercontent.com/21249611/114312560-4b8a0900-9af3-11eb-9931-69dbd02a6024.png" width="800" />

<img src="https://user-images.githubusercontent.com/21249611/114312599-76745d00-9af3-11eb-9561-6dfdbbae0511.png" width="800" />

**Comment by andstor** [comment]
What do you think @hgeorgsch ?

**Comment by hgeorgsch** [comment]
This looks very good.
We may want to emphasise «superseded by» rather than «referenced by».  We may need referencing, but the main use case I am concerned with is superseding issues, making it clear that the superseded issue is no longer relevant, which is not the case for referenced issues.
