### ISSUE TITLE
Block view API

### ISSUE THREAD

**Issue by andstor** [KQMATH/moodle-local_qtracker#3]
For registering new Moodle question issues, an API should be created for generating the appropriate UI.

The UI needs to be fit for use in a Moodle block. See KQMATH/moodle-block_quizqtracker#1

**Comment by hgeorgsch** [comment]
Close this, @andstor ?

**Comment by andstor** [comment]
I think we can leave this open, as I would like to refine the API a tiny bit.

**Comment by hgeorgsch** [comment]
Anything in particular that you have in mind?  It is a little too vague as phrased I think :-)

**Comment by andstor** [comment]
I think we can close this.. The API is fine for now 👍
