### ISSUE TITLE
Cancel button in new_issue.php redirects to non-existent file new_issues.php

### ISSUE THREAD

**Issue by XiRouz** [KQMATH/moodle-local_qtracker#54]
$returnurl on line 50 is set as "new \moodle_url('/local/qtracker/new_issues.php');". Is it misspelled and supposed to redirect to issues.php, or authors forgot to add a file to plugin?

**Comment by jorgenfinsveen** [comment]
Typo resolved in branch __bug/#54__. Pull request created.
