### ISSUE TITLE
View issue

### ISSUE THREAD

**Issue by andstor** [KQMATH/moodle-local_qtracker#9]
As a teacher, I want to be able to view the details of a registered issue. I also need to be able to have quick access to the related Moodle question. This way, I am able to quickly resolve the issue.

**Comment by andstor** [comment]
### Mockup of the issue view.
#### Question
The question section should be expandable, and contains a small preview of the question. Including title and description.
The sidebar contains action links for quick access to editing and preview the question.

#### Issue
The issue section contains a "conversation" styled layout. The first comment is the initial description of the question issue. By using the textfield at the bottom, one can make new comments. By clicking the close button, the issue will be closed.
The sidebar contains two sections. One for managing labels, and one for referencing/linking other related issues.

<img src="https://user-images.githubusercontent.com/21249611/90021437-8eb88180-dcb1-11ea-95a3-93b043b75281.png" width="500"  />

**Comment by andstor** [comment]
What do you think @hgeorgsch ?

**Comment by hgeorgsch** [comment]
I think i looks good.  There are several more detailed features to add, but I'll create specific issues for that.
Close this. @andstor ?

**Comment by andstor** [comment]
Yes, i think we can close this.
